version: "3"

services:
  web:
    build: ./web
    container_name: joomla_web
    working_dir: ${WEB_PATH_PROJECT_INSIDE_CONTAINER}
    volumes:
      - "${WEB_PATH_PROJECT}:${WEB_PATH_PROJECT_INSIDE_CONTAINER}"
      - "${WEB_PATH_PROJECT}/docker/web/php.ini:/etc/php/7.0/apache2/php.ini"
    ports:
      - "${WEB_PORT}:80"
    links:
      - "mysql"
      - "phpmyadmin"
  mysql:
    image: mysql:latest
    container_name: joomla_db
    volumes:
      - "${MYSQL_LOCAL_DB}:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: joomla_pma
    restart: always
    volumes:
      - /sessions
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      PMA_HOST: "mysql"
    ports:
      - "${PMA_PORT}:80"
    links:
      - "mysql"